# **Tensorflow Tutorial 01**

In [9]:
import os

os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"

import tensorflow as tf
physical_devices = tf.config.list_physical_devices('GPU')
tf.config.experimental.set_memory_growth(physical_devices[0], True)



""" Initilization """
x = tf.constant(4, shape=(1,1), dtype=tf.float32)
print(x)
# output -> tf.Tensor([[4.]], shape=(1, 1), dtype=float32)
x = tf.constant([[1,2,3],[4,5,6]])
print(x)
# Output ->
# tf.Tensor(
# [[1 2 3]
#  [4 5 6]], shape=(2, 3), dtype=int32)

x = tf.ones((3,3)) 
print(x)
# Output ->
# tf.Tensor(
# [[1. 1. 1.]
#  [1. 1. 1.]
#  [1. 1. 1.]], shape=(3, 3), dtype=float32)

x = tf.zeros((2, 3))
x = tf.eye(3)  # "I" for the identity matrix(eye)
print(x)
# Output ->
# tf.Tensor(
# [[1. 0. 0.]
#  [0. 1. 0.]
#  [0. 0. 1.]], shape=(3, 3), dtype=float32)

x = tf.random.normal((3, 3), mean=0, stddev=1) # random number with standard normal distribuition range[-1,1]
print(x)
# Output ->
# tf.Tensor(
# [[ 0.4738859  -0.6032325   1.9088216 ]
#  [-1.9356626   0.505961   -0.40719536]
#  [-1.0908657  -0.2582672  -1.4088856 ]], shape=(3, 3), dtype=float32)

x = tf.random.uniform((1, 3), minval=0, maxval=1)   # uniform distribiution range[0,1]
x= tf.range(start=1, limit=10, delta=2)
print(x)
# Output -> tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)

x = tf.cast(x, dtype=tf.float64)
print(x) 
# tf.float (16, 32,64), tf.int(8, 16, 32, 64), tf.bool

"""Mathematical Operations """
x = tf.constant([1,2,3])
y = tf.constant([4,5,6])
z = tf.add(x, y)
# or z = x + y
print(z)
# Output ->. tf.Tensor([5 7 9], shape=(3,), dtype=int32)

z = tf.divide(x, y)
x = x / y

# z = tf.multiply(x, y)
# z = x * y

# z = tf.tensordot(x, y, axes=1)
# print(z)

# z = tf.reduce_sum(x*y, axis=0)
# print(z)

z = x ** 5
print(z)


x = tf.random.normal((2, 3))
y = tf.random.normal((3, 4))
z = tf.matmul(x, y)
print(z)
# Output ->
# tf.Tensor(
# [[-1.2695736   0.18700266 -0.87645066 -0.64774853]
#  [-1.0367346  -2.200025   -3.9524362   3.1036966 ]], shape=(2, 4), dtype=float32)
# Below code is also show you the same result
# z = x @ y
# print(z)


""" Indexing """
x = tf.constant([0, 1, 1, 2, 3, 1, 2])
print(x[:])    # tf.Tensor([0 1 1 2 3 1 2], shape=(7,), dtype=int32)
print(x[1:])   # tf.Tensor([1 1 2 3 1 2], shape=(6,), dtype=int32)
print(x[1:3])  # tf.Tensor([1 1], shape=(2,), dtype=int32)
print(x[::2])  # tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)
print(x[::-1]) # tf.Tensor([2 1 3 2 1 1 0], shape=(7,), dtype=int32)

indics = tf.constant([0, 3])
x_ind = tf.gather(x, indics)
print(x_ind)  # Extracting indices

x = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])
print(x[0, :])
print(x[0:2, :])


""" Reshaping """
x = tf.range(9)
print(x)
x = tf.reshape(x, (3, 3))
print(x)
x = tf.transpose(x, perm=[1, 0])    # perm : permutation
print(x)

In [14]:
""" Reshaping """
x = tf.range(9)
print(x)
x = tf.reshape(x, (3, 3))
print(x)
x = tf.transpose(x, perm=[1, 0])
print(x)